[features]
seeds = false
skip-lint = false

[programs.devnet]
staking_contract = "9amNgcg3UHf5udr3gJ4xJpgqUqx3BF1i9vB5Np8xTH2i"

[programs.localnet]
staking_contract = "9amNgcg3UHf5udr3gJ4xJpgqUqx3BF1i9vB5Np8xTH2i"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/ant/.config/solana/id.json"

[scripts]
test = "npx mocha ./tests"
