// exports.admin = // add admin secretKey here
// exports.user1 = // add user1 secretKey here
// exports.user2 = // add user2 secretKey here
// exports.user3 = // add user3 secretKey here
// exports.user4 = // add user4 secretKey here
// exports.user5 = // add user5 secretKey here
// exports.programIdRaw = "" // add program id here
// exports.mintIdRaw = "" // add mintKey here
// exports.stateSeed = "" // add state seedphrase here
// exports.escrowSeed = "" // add escrow seedphrase here
// exports.stakingInfoPdaSeed = "" // add staking info seedphrase here
// exports.stateSeedTest = "" // add state seedphrase here
// exports.escrowSeedTest = "" // add escrow seedphrase here
// exports.stakingInfoPdaSeedTest = "" // add staking info seedphrase here