exports.admin = // add admin secretKey here
exports.user1 = // add user1 secretKey here
exports.user2 = // add user2 secretKey here
exports.user3 = // add user3 secretKey here
exports.user4 = // add user4 secretKey here
exports.user5 = // add user5 secretKey here
exports.programIdRaw = ""
exports.mintIdRaw = ""
exports.stateSeed = ""
exports.escrowSeed = ""
exports.stakingInfoPdaSeed = ""